const translations = {
    titleBiography: {
        italian: "Biografia",
        english: "Biography",
    },
    biography: {
        italian: `Ekaterina Dolgasheva, soprano, nasce a Cheboksary (Russia) il 20 marzo 1990. Si diploma con lode nel 2009 all'Istituto di Musica 'Pavlova F.P.' come artista di coro e complesso musicale. Nel 2015, dopo essersi trasferita a Mosca, ottiene il diploma di Cantante lirica presso l'Accademia Russa di Musica 'Gnessin', debuttando nei ruoli di Susanna in 'Le nozze di Figaro' di W.A. Mozart e di Musetta in 'La Bohème' di G. Puccini al teatro di Gnessin.</br></br> Nel 2016 completa gli studi al Conservatorio 'O. Respighi' di Latina con voto 110/110. Ha frequentato masterclass con maestri come Raúl Giménez, Ramon de Andrés, Vivica Genaux, Patrizia Ciofi e Chris Merritt.</br></br> Nel 2014 vince il 1° premio al Concorso Sochi Art World (Russia) e nel 2018 il 3° premio al 17° Concorso Internazionale di Musica 'Città di Caserta' Belvedere di San Leucio (Italia). È finalista al 4° Concorso Internazionale di Canto Lirico 'Città di Roma Caput Mundi' e al Concorso Lirico Internazionale 'Città di Prato' nel 2022.</br></br> Nel 2023 interpreta Musetta in 'La Bohème' di Puccini all'Accademia Dell'Arte Dello Spettacolo ADADS. Dal 2010 ad oggi, si è esibita in numerosi concerti da solista in Russia, Spagna, Ucraina e Italia, collaborando con varie associazioni musicali.`,
        english: `Ekaterina Dolgasheva, soprano, was born in Cheboksary (Russia) on March 20, 1990. She graduated with honors in 2009 from the Pavlova F.P. Music Institute as a choir and ensemble artist. In 2015, after moving to Moscow, she obtained her diploma in opera singing from the Gnessin Russian Academy of Music, debuting as Susanna in W.A. Mozart's 'The Marriage of Figaro' and Musetta in G. Puccini's 'La Bohème' at the Gnessin Theater.</br></br> In 2016, she completed her studies at the O. Respighi Conservatory in Latina, achieving a perfect score of 110/110. She has attended masterclasses with renowned maestros such as Raúl Giménez, Ramon de Andrés, Vivica Genaux, Patrizia Ciofi, and Chris Merritt.</br></br> In 2014, she won 1st prize at the Sochi Art World Competition (Russia) and in 2018, 3rd prize at the 17th International Music Competition 'Città di Caserta' Belvedere di San Leucio (Italy). She was a finalist at the 4th International Opera Singing Competition 'Città di Roma Caput Mundi' and the International Opera Competition 'Città di Prato' in 2022.</br></br> In 2023, she performed the role of Musetta in Puccini's 'La Bohème' at the ADADS Academy of Performing Arts. From 2010 to the present, she has appeared in numerous solo concerts in Russia, Spain, Ukraine, and Italy, collaborating with various musical associations.`
    }
}
